### ISSUE TITLE
Criativo 1 - Warm Up

### ISSUE THREAD

**Issue by helenafreitas5** [w3b3d3v/squad-midiatico-content-PT#176]
![Image](https://github.com/w3b3d3v/team-content-PT/assets/98783850/2a544ebe-2a45-495c-b71f-7d534f9343e6)

1 carrossel sobre a rede stellar, divulgando no final o grupo de estudos

**Comment by viniblack** [comment]
https://www.canva.com/design/DAGJJ12bfew/oD6r1qTUtwSDvkSxX7tbuA/edit?utm_content=DAGJJ12bfew&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton



[PT Warm up STELLAR.pdf](https://github.com/user-attachments/files/16018572/PT.Warm.up.STELLAR.pdf)

**Comment by JennyT3** [comment]
🪐 Stellar es una Blockchain dedicada a entregar productos financieros a la población sin acceso a los bancos. Con su nueva plataforma de Smart Contracts Soroban, puedes crear el futuro de las finanzas y encontrar financiamiento de hasta 100k USD con el programa Stellar Community Fund 

¡Únete a la mayor comunidad de desarrolladores web3 en América Latina! 🚀
En Web3Dev, nos enfocamos en Comunidad, Educación y Construcción. Conecta con desarrolladores, aprende sobre tecnologías web3 y colabora en proyectos innovadores. ¡Forma parte del futuro del ecosistema web3!

🌐 Sitio web https://www.w3d.community/
💬 Discord https://discord.com/invite/4QQNdypNay


🥑 PaltaLabs es un equipo de Chilenos creando productos de Finanzas Descentralizadas en la Blockchain de Stellar. Su primer producto es un Exchange Descentralizado (AMM) llamado Soroswap.Finance 🪐

https://paltalabs.io/
https://soroswap.finance/
