### ISSUE TITLE
Criativo 3 - Lançamento - Post Feed

### ISSUE THREAD

**Issue by helenafreitas5** [w3b3d3v/squad-midiatico-content-PT#178]
![Image](https://github.com/w3b3d3v/team-content-PT/assets/98783850/2bc8afc0-7dc0-425e-9a89-a515c7141c8c)

1 post reforçando que ainda 
dá para se inscrever + Benefícios do grupo de estudo

Direcional Legenda, -> mudar com o tom de voz da web3dev

DIRECIONAL LEGENDA: 
Ainda não se inscreveu?
Aqui estão 3 benefícios para você não ficar de fora!

1️⃣ Networking Incrível: Conecte-se com especialistas e entusiastas da blockchain.
2️⃣ Aprendizado Prático: Desde a criação de wallets até smart contracts avançados. (adicionar outcomes do grupo de estudo)
3️⃣ Certificado de Participação: Valide seu conhecimento com um certificado exclusivo.

Junte-se a nós nas próximas quartas-feiras às 11 AM GMT-3 no Discord! 🚀
Link na bio para mais informações.

adicionar datas do grupo de estudo
#Blockchain #Stellar #EstudoBlockchain #Cripto #Desenvolvimento #GrupoDeEstudos

**Comment by viniblack** [comment]
https://www.canva.com/design/DAGJQzkGqV4/Wz3eZky5If7AW329JKfwhw/edit?utm_content=DAGJQzkGqV4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

[Criativo 3 - Lançamento - Post Feed (1).pdf](https://github.com/user-attachments/files/15996036/Criativo.3.-.Lancamento.-.Post.Feed.1.pdf)

**Comment by JennyT3** [comment]
agora está tudo em espanhol

**Comment by helenafreitas5** [comment]
boua, ficou otimo galera, valeu!
